# Generated by Django 5.0.4 on 2024-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(blank=True, max_length=30)),
                ('browser_title', models.CharField(blank=True, max_length=30)),
                ('panel_title', models.CharField(blank=True, max_length=30)),
                ('logo_image', models.CharField(blank=True, max_length=30)),
                ('logo_image_url', models.TextField(blank=True)),
                ('light_logo', models.CharField(blank=True, max_length=30)),
                ('light_logo_url', models.TextField(blank=True)),
                ('dark_logo', models.CharField(blank=True, max_length=30)),
                ('dark_logo_url', models.TextField(blank=True)),
                ('favicon', models.CharField(blank=True, max_length=30)),
                ('favicon_url', models.TextField(blank=True)),
                ('copyright', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'main_detail',
            },
        ),
    ]
